name: aqi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - mlflow
  - numpy
  - joblib
  - tensorflow==2.18.0
  - pip
  - pip:
    - ipykernel 
    - protobuf<=3.20.1 
