name: Train AQI Model and Upload Artifacts

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache conda environment
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs/aqi-env
          key: ${{ runner.os }}-conda-env-${{ hashFiles('MLProject/conda.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-env-

      - name: Set up Miniconda with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: aqi-env
          environment-file: MLProject/conda.yml
          auto-activate-base: false
          python-version: 3.10
          use-mamba: true

      - name: Run MLflow project
        run: |
          mlflow run MLProject/ --env-manager=local

      - name: Upload MLflow model artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/mlruns/**/artifacts/model
